-- Clear existing products and bundles
TRUNCATE TABLE public.cart_items CASCADE;
TRUNCATE TABLE public.saved_items CASCADE;
TRUNCATE TABLE public.bundles CASCADE;
TRUNCATE TABLE public.products RESTART IDENTITY CASCADE;

INSERT INTO public.products (category, name, brand, price, tags, rating, delivery_days) VALUES
-- CATEGORY 1: Health & Body Problems (15)
('health', 'Moov Pain Relief Spray', 'Moov', 180, '{"pain","body","muscle"}', 4.5, 2),
('health', 'Volini Gel 50g', 'Volini', 220, '{"pain","muscle","back"}', 4.6, 2),
('health', 'Dr. Ortho Knee Support', 'Dr.Ortho', 450, '{"knee","joint","pain"}', 4.3, 3),
('health', 'Tynor Posture Corrector', 'Tynor', 799, '{"posture","back","spine"}', 4.2, 4),
('health', 'Ortho Footwear Slippers', 'Ortho', 1200, '{"foot","pain","heel"}', 4.7, 5),
('health', 'Heating Pad Electric', 'Wellbeing', 599, '{"pain","heat","muscle"}', 4.4, 3),
('health', 'Tiger Balm Red', 'Tiger Balm', 149, '{"pain","headache","muscle"}', 4.8, 2),
('health', 'Cervical Pillow', 'Sleepsia', 849, '{"neck","cervical","sleep","pain"}', 4.1, 4),
('health', 'Back Support Belt', 'Tynor', 699, '{"back","spine","posture"}', 4.3, 3),
('health', 'Ayurvedic Pain Oil', 'Dabur', 250, '{"pain","ayurvedic","natural"}', 4.0, 3),
('health', 'Knee Cap Pair', 'Strauss', 299, '{"knee","joint","support"}', 4.2, 3),
('health', 'Eye Drops Lubricating', 'Rohto', 180, '{"eye","strain","dryness"}', 4.6, 2),
('health', 'Blue Light Glasses', 'Specsy', 599, '{"eye","screen","strain"}', 4.3, 4),
('health', 'Compression Socks', 'Tynor', 349, '{"leg","circulation","pain"}', 4.1, 3),
('health', 'Cold Hot Gel Pack', 'Doff', 349, '{"pain","swelling","injury"}', 4.4, 3),

-- CATEGORY 2: Sleep Problems (10)
('sleep', 'Cervical Memory Foam Pillow', 'Sleepsia', 999, '{"sleep","neck","pillow"}', 4.5, 3),
('sleep', 'Weighted Blanket', 'Dreamz', 2499, '{"sleep","anxiety","comfort"}', 4.3, 5),
('sleep', 'White Noise Machine', 'LectroFan', 2999, '{"sleep","noise","relax"}', 4.4, 4),
('sleep', 'Sleep Mask Eye Cover', 'Boldfit', 199, '{"sleep","dark","rest"}', 4.5, 2),
('sleep', 'Lavender Pillow Spray', 'The Body Shop', 599, '{"sleep","relax","aroma"}', 4.6, 3),
('sleep', 'Melatonin Gummies', 'Wellbeing Nutrition', 599, '{"sleep","supplement"}', 4.2, 3),
('sleep', 'Earplugs for Sleep', '3M', 149, '{"sleep","noise","quiet"}', 4.7, 2),
('sleep', 'Chamomile Tea Pack', 'Organic India', 299, '{"sleep","tea","relax"}', 4.8, 2),
('sleep', 'Anti Snore Chin Strap', 'Breathe Right', 449, '{"sleep","snoring"}', 3.9, 4),
('sleep', 'Aromatherapy Diffuser', 'Iris', 799, '{"sleep","aroma","relax"}', 4.4, 3),

-- CATEGORY 3: Study & Focus Problems (12)
('study', 'Philips Study Lamp LED', 'Philips', 899, '{"study","light","focus"}', 4.6, 2),
('study', 'Classmate Notebook Set', 'Classmate', 199, '{"study","notes","college"}', 4.8, 2),
('study', 'Noise Cancelling Headphones', 'Noise', 1499, '{"study","focus","silence"}', 4.2, 3),
('study', 'Wooden Desk Organizer', 'Officepoint', 349, '{"study","desk","organize"}', 4.5, 5),
('study', 'Casio Scientific Calculator', 'Casio', 599, '{"study","math","calculator"}', 4.9, 2),
('study', 'Sticky Notes Multicolor', '3M Post-it', 129, '{"study","notes","organize"}', 4.7, 2),
('study', 'Laptop Stand Adjustable', 'AmazonBasics', 799, '{"study","laptop","ergonomic"}', 4.4, 3),
('study', 'Pomodoro Timer', 'Time Timer', 299, '{"study","focus","time"}', 4.0, 5),
('study', 'Mini Whiteboard A3', 'Luxor', 449, '{"study","plan","write"}', 4.1, 4),
('study', 'Highlighter Set 6 colors', 'Stabilo', 149, '{"study","highlight","notes"}', 4.7, 2),
('study', 'Flash Card Set Blank', 'Classmate', 99, '{"study","memory","revision"}', 4.5, 3),
('study', 'Study Chair Cushion', 'Wakefit', 799, '{"study","comfort","sitting"}', 4.3, 4),

-- CATEGORY 4: Gym & Fitness Problems (12)
('gym', 'Boldfit Resistance Bands Set', 'Boldfit', 399, '{"gym","workout","fitness"}', 4.4, 3),
('gym', 'Strauss Yoga Mat 6mm', 'Strauss', 599, '{"gym","yoga","exercise"}', 4.5, 2),
('gym', 'Protein Shaker Bottle', 'Boldfit', 299, '{"gym","protein","fitness"}', 4.6, 2),
('gym', 'Gym Gloves', 'Kobo', 349, '{"gym","gloves","workout"}', 4.2, 3),
('gym', 'MuscleBlaze Whey Protein', 'MuscleBlaze', 1999, '{"gym","protein","muscle"}', 4.7, 2),
('gym', 'Jump Rope Speed', 'Boldfit', 199, '{"gym","cardio","fitness"}', 4.3, 3),
('gym', 'Gym Bag Duffle', 'Wildcraft', 699, '{"gym","bag","sports"}', 4.6, 4),
('gym', 'Ankle Support Pair', 'Strauss', 299, '{"gym","ankle","support"}', 4.4, 3),
('gym', 'Workout Towel', 'Burnlab', 249, '{"gym","towel","sweat"}', 4.5, 3),
('gym', 'Gym Headband', 'Nivia', 149, '{"gym","head","sweat"}', 4.1, 4),
('gym', 'Ab Roller Wheel', 'Kobo', 449, '{"gym","abs","core"}', 4.3, 3),
('gym', 'Foam Roller', 'Boldfit', 599, '{"gym","recovery","muscle"}', 4.5, 3),

-- CATEGORY 5: Electrical & Home Problems (10)
('electrical', 'Extension Board 4 Socket', 'Havells', 349, '{"electrical","socket","home"}', 4.5, 2),
('electrical', 'LED Bulb Pack 4', 'Philips', 299, '{"electrical","light","home"}', 4.7, 2),
('electrical', 'Voltage Stabilizer', 'V-Guard', 1299, '{"electrical","voltage","appliance"}', 4.4, 4),
('electrical', 'Power Strip Surge', 'Belkin', 999, '{"electrical","surge","protect"}', 4.6, 3),
('electrical', 'Cable Management Box', 'D-Line', 349, '{"electrical","cable","organize"}', 4.3, 4),
('electrical', 'Smart Plug WiFi', 'TP-Link', 799, '{"electrical","smart","home"}', 4.5, 3),
('electrical', 'LED Strip Lights', 'Syska', 499, '{"electrical","light","decoration"}', 4.2, 3),
('electrical', 'Emergency LED Torch', 'Eveready', 249, '{"electrical","torch","emergency"}', 4.6, 2),
('electrical', 'UPS for Router', 'APC', 1499, '{"electrical","ups","internet"}', 4.4, 5),
('electrical', 'Wire Cutter Set', 'Stanley', 399, '{"electrical","tools","repair"}', 4.5, 3),

-- CATEGORY 6: Kitchen Problems (12)
('kitchen', 'Prestige Pressure Cooker', 'Prestige', 999, '{"kitchen","cook","pressure"}', 4.8, 3),
('kitchen', 'Milton Casserole Set', 'Milton', 699, '{"kitchen","food","storage"}', 4.5, 3),
('kitchen', 'Knife Set Stainless', 'Victorinox', 1299, '{"kitchen","knife","cooking"}', 4.6, 4),
('kitchen', 'Cutting Board Bamboo', 'Cello', 299, '{"kitchen","cut","cook"}', 4.4, 3),
('kitchen', 'Non Stick Tawa 26cm', 'Hawkins', 499, '{"kitchen","tawa","cook"}', 4.3, 3),
('kitchen', 'Mixer Grinder 500W', 'Philips', 2499, '{"kitchen","mixer","grind"}', 4.7, 5),
('kitchen', 'Steel Containers Set', 'Vaya', 799, '{"kitchen","storage","steel"}', 4.5, 3),
('kitchen', 'Vegetable Chopper', 'Ganesh', 349, '{"kitchen","chop","vegetable"}', 4.2, 3),
('kitchen', 'Oil Dispenser Glass', 'Borosil', 299, '{"kitchen","oil","dispense"}', 4.4, 3),
('kitchen', 'Spice Rack Organizer', 'Cello', 449, '{"kitchen","spice","organize"}', 4.3, 4),
('kitchen', 'Induction Cooktop', 'Pigeon', 1499, '{"kitchen","induction","cook"}', 4.5, 4),
('kitchen', 'Water Purifier Pitcher', 'Tata Swach', 799, '{"kitchen","water","purify"}', 4.6, 3),

-- CATEGORY 7: Shoe & Footwear Problems (8)
('footwear', 'Shoe Cleaning Kit', 'Reshoevn8r', 599, '{"shoe","clean","repair"}', 4.3, 4),
('footwear', 'Shoe Polish Black', 'Cherry Blossom', 99, '{"shoe","polish","leather"}', 4.5, 2),
('footwear', 'Shoe Stretcher Pair', 'Etrendz', 349, '{"shoe","stretch","comfort"}', 4.2, 5),
('footwear', 'Insole Gel Cushion', 'Scholl', 399, '{"shoe","insole","comfort","foot"}', 4.6, 3),
('footwear', 'Waterproof Shoe Spray', 'Scotchgard', 499, '{"shoe","waterproof","protect"}', 4.4, 4),
('footwear', 'Shoe Rack 3 Tier', 'Nilkamal', 799, '{"shoe","rack","organize"}', 4.3, 5),
('footwear', 'Heel Grip Pads', 'Carnation', 199, '{"shoe","heel","comfort"}', 4.5, 3),
('footwear', 'Shoe Deodorizer Spray', 'Kaps', 249, '{"shoe","smell","clean"}', 4.4, 3),

-- CATEGORY 8: Festival & Celebration (12)
('festival', 'Fairy Lights LED 10m', 'Syska', 299, '{"festival","lights","decoration"}', 4.6, 2),
('festival', 'Rangoli Colors Set', 'Camel', 149, '{"festival","rangoli","diwali"}', 4.5, 2),
('festival', 'Diyas Clay Set 20pcs', 'Craftvatika', 199, '{"festival","diwali","diya"}', 4.8, 3),
('festival', 'Puja Thali Set', 'Craftsman', 599, '{"festival","puja","pooja"}', 4.4, 4),
('festival', 'Gift Wrapping Paper Set', 'Archies', 149, '{"festival","gift","wrap"}', 4.5, 2),
('festival', 'Scented Candles Set', 'Iris', 449, '{"festival","candle","aroma"}', 4.6, 3),
('festival', 'Balloon Pack 100pcs', 'Party Propz', 199, '{"festival","balloon","party"}', 4.3, 2),
('festival', 'Paper Lanterns Set', 'Wrapaholic', 299, '{"festival","lantern","decor"}', 4.4, 3),
('festival', 'Incense Sticks Box', 'Cycle Pure', 99, '{"festival","agarbatti","puja"}', 4.7, 2),
('festival', 'Return Gifts Box Set', 'Archies', 499, '{"festival","gifts","return"}', 4.3, 4),
('festival', 'Flower Garland Artificial', 'Craftvatika', 249, '{"festival","flower","decor"}', 4.5, 3),
('festival', 'Pooja Samagri Kit', 'Patanjali', 349, '{"festival","puja","pooja"}', 4.6, 2),

-- CATEGORY 9: Occasion Planning (10)
('occasion', 'Photo Frame Collage', 'Archies', 599, '{"occasion","birthday","gift","photo"}', 4.3, 4),
('occasion', 'Fastrack Analog Watch', 'Fastrack', 1299, '{"occasion","gift","birthday"}', 4.6, 3),
('occasion', 'boAt Rockerz Earphones', 'boAt', 999, '{"occasion","gift","birthday"}', 4.5, 2),
('occasion', 'Cadbury Celebrations Box', 'Cadbury', 499, '{"occasion","chocolate","gift"}', 4.8, 2),
('occasion', 'Personalised Mug', 'Presto', 349, '{"occasion","mug","gift","custom"}', 4.5, 5),
('occasion', 'Journal Notebook Premium', 'Paperage', 399, '{"occasion","gift","journal"}', 4.8, 3),
('occasion', 'Leather Wallet Men', 'Wildhorn', 699, '{"occasion","gift","wallet"}', 4.6, 3),
('occasion', 'Scarf Silk Women', 'FabIndia', 599, '{"occasion","gift","women"}', 4.4, 4),
('occasion', 'Bluetooth Speaker Mini', 'boAt', 1299, '{"occasion","gift","speaker"}', 4.7, 2),
('occasion', 'Customized Keychain', 'The Crazy Me', 199, '{"occasion","gift","keychain"}', 4.4, 5),

-- CATEGORY 10: School Starts (10)
('school', 'School Bag 20L', 'Wildcraft', 999, '{"school","bag","student"}', 4.7, 3),
('school', 'Geometry Box', 'Classmate', 149, '{"school","math","geometry"}', 4.5, 2),
('school', 'Cello Pens Set 10', 'Cello', 99, '{"school","pen","write"}', 4.6, 2),
('school', 'Colour Pencils 24', 'Apsara', 149, '{"school","art","colour"}', 4.8, 2),
('school', 'Tiffin Box Steel', 'Vaya', 599, '{"school","lunch","tiffin"}', 4.6, 3),
('school', 'Water Bottle Kids', 'Milton', 249, '{"school","water","bottle"}', 4.7, 2),
('school', 'Ruler Scale Set', 'Classmate', 49, '{"school","ruler","geometry"}', 4.4, 2),
('school', 'Eraser Sharpener Set', 'Apsara', 49, '{"school","erase","sharpen"}', 4.6, 2),
('school', 'Sticky Labels Name', 'Avery', 99, '{"school","label","name"}', 4.3, 3),
('school', 'Sketch Pens Set 12', 'Camlin', 99, '{"school","art","sketch"}', 4.7, 2),

-- CATEGORY 11: College Starts (10)
('college', 'Wildcraft Backpack 30L', 'Wildcraft', 1299, '{"college","bag","student"}', 4.7, 3),
('college', 'USB-C Hub 7-in-1', 'Portronics', 499, '{"college","laptop","hub"}', 4.2, 4),
('college', 'Scientific Calculator', 'Casio', 599, '{"college","math","calculator"}', 4.9, 2),
('college', 'Highlighter Set 6', 'Stabilo', 149, '{"college","study","highlight"}', 4.7, 2),
('college', 'Stapler Set', 'Kangaro', 149, '{"college","office","stapler"}', 4.5, 2),
('college', 'Lunch Box Steel', 'Milton', 399, '{"college","lunch","tiffin"}', 4.6, 3),
('college', 'Umbrella Compact', 'Rainco', 299, '{"college","rain","umbrella"}', 4.3, 3),
('college', 'ID Card Holder', 'Durable', 99, '{"college","id","holder"}', 4.1, 3),
('college', 'Notebook Spiral A4', 'Classmate', 89, '{"college","notes","notebook"}', 4.5, 2),
('college', 'Pen Drive 32GB', 'SanDisk', 349, '{"college","storage","pendrive"}', 4.8, 2),

-- CATEGORY 12: Home Convenience (10)
('home', 'Bombay Dyeing Bedsheet', 'Bombay Dyeing', 799, '{"home","bed","comfort"}', 4.5, 3),
('home', 'Nilkamal Plastic Shelf', 'Nilkamal', 1499, '{"home","storage","shelf"}', 4.2, 5),
('home', 'Bathroom Organizer', 'Cello', 449, '{"home","bathroom","organize"}', 4.3, 4),
('home', 'Wall Clock Modern', 'Ajanta', 399, '{"home","clock","wall"}', 4.4, 3),
('home', 'Door Mat Anti Slip', 'Story@Home', 199, '{"home","door","mat"}', 4.0, 3),
('home', 'Laundry Bag Large', 'House of Quirk', 249, '{"home","laundry","bag"}', 4.1, 4),
('home', 'Milton Water Bottle', 'Milton', 349, '{"home","water","bottle"}', 4.6, 2),
('home', 'Hangers Pack 20', 'Parasnath', 199, '{"home","hanger","clothes"}', 4.3, 3),
('home', 'Vacuum Storage Bags', 'Spacesaver', 599, '{"home","storage","space"}', 4.5, 4),
('home', 'Under Bed Storage Box', 'Sterilite', 799, '{"home","storage","organize"}', 4.4, 5),

-- CATEGORY 13: New Home Setup (10)
('new-home', 'Godrej Door Lock', 'Godrej', 1299, '{"new-home","lock","security"}', 4.7, 3),
('new-home', 'Bajaj Ceiling Fan', 'Bajaj', 1799, '{"new-home","fan","electrical"}', 4.5, 4),
('new-home', 'Mosquito Racket Bat', 'HIT', 299, '{"new-home","mosquito","pest"}', 4.2, 2),
('new-home', 'Garbage Bins Set 3', 'Tramontina', 449, '{"new-home","bin","waste"}', 4.4, 4),
('new-home', 'Toolkit Basic Set', 'Stanley', 699, '{"new-home","tools","repair"}', 4.6, 3),
('new-home', 'First Aid Box', 'Johnson', 499, '{"new-home","medical","safety"}', 4.5, 2),
('new-home', 'Doorbell Wireless', 'Honeywell', 599, '{"new-home","doorbell","security"}', 4.3, 3),
('new-home', 'Smoke Detector', 'Kidde', 799, '{"new-home","safety","smoke"}', 4.2, 4),
('new-home', 'Curtain Rods Set', 'Furnishing Zone', 399, '{"new-home","curtain","window"}', 4.1, 5),
('new-home', 'Air Freshener Set', 'Ambi Pur', 249, '{"new-home","smell","fresh"}', 4.4, 2),

-- CATEGORY 14: Tech Problems (12)
('tech', 'Laptop Cooling Pad', 'Portronics', 799, '{"tech","laptop","cooling"}', 4.4, 3),
('tech', 'Screen Cleaning Kit', 'Windex', 299, '{"tech","screen","clean"}', 4.6, 2),
('tech', 'Cable Organizer Clips', 'Bluelounge', 199, '{"tech","cable","organize"}', 4.3, 3),
('tech', 'USB Hub 4 Port', 'Portronics', 399, '{"tech","usb","hub"}', 4.5, 3),
('tech', 'Wireless Mouse', 'Logitech', 799, '{"tech","mouse","wireless"}', 4.7, 2),
('tech', 'Keyboard Wrist Rest', 'Fellowes', 499, '{"tech","keyboard","ergonomic"}', 4.4, 4),
('tech', 'Phone Stand Adjustable', 'Lamicall', 299, '{"tech","phone","stand"}', 4.5, 3),
('tech', 'Webcam 1080p', 'Logitech', 1299, '{"tech","webcam","video"}', 4.5, 3),
('tech', 'Laptop Sleeve 15 inch', 'Inateck', 599, '{"tech","laptop","protect"}', 4.6, 3),
('tech', 'Power Bank 20000mAh', 'Mi', 999, '{"tech","power","battery"}', 4.7, 2),
('tech', 'Ethernet Cable 5m', 'D-Link', 199, '{"tech","internet","cable"}', 4.5, 2),
('tech', 'Screen Privacy Filter', '3M', 999, '{"tech","screen","privacy"}', 4.3, 4),

-- CATEGORY 15: Creator & YouTube Setup (10)
('creator', 'Digitek Tripod 7ft', 'Digitek', 999, '{"creator","tripod","youtube"}', 4.4, 3),
('creator', 'Maono Ring Light 10inch', 'Maono', 1499, '{"creator","light","youtube"}', 4.5, 4),
('creator', 'BM800 Condenser Mic', 'BM800', 799, '{"creator","mic","audio"}', 4.0, 5),
('creator', 'Green Screen Cloth', 'Emart', 699, '{"creator","green screen","youtube"}', 4.2, 4),
('creator', 'SD Card 64GB', 'SanDisk', 499, '{"creator","storage","camera"}', 4.8, 2),
('creator', 'Microphone Pop Filter', 'Neewer', 249, '{"creator","mic","audio"}', 4.4, 3),
('creator', 'HDMI Cable 2m', 'AmazonBasics', 299, '{"creator","hdmi","display"}', 4.6, 2),
('creator', 'Laptop Stand Foldable', 'AmazonBasics', 599, '{"creator","laptop","stand"}', 4.3, 3),
('creator', 'Webcam 1080p HD', 'Logitech', 1299, '{"creator","webcam","video"}', 4.5, 3),
('creator', 'Cable Management Box', 'D-Line', 349, '{"creator","cable","organize"}', 4.3, 4);
